'use strict';
const fs = require('node:fs/promises');
const fsSync = require('node:fs');
const path = require('node:path');
const { spawn } = require('node:child_process');
const net = require('node:net');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
(async () => {
  const root = path.resolve(__dirname, '..');
  const directory = path.join(root, 'artifacts/native-ui');
  await fs.mkdir(directory, { recursive: true });
  for (const filename of ['ready', 'done', 'notes.md']) await fs.rm(path.join(directory, filename), { force: true });
  const listener = net.createServer();
  await new Promise(resolve => listener.listen(0, '127.0.0.1', resolve));
  const port = listener.address().port;
  await new Promise(resolve => listener.close(resolve));
  const env = { ...process.env }; delete env.ELECTRON_RUN_AS_NODE;
  const executable = path.join(process.env.LOCALAPPDATA, 'Programs/Microsoft VS Code/Code.exe');
  const log = fsSync.openSync(path.join(directory, 'host.log'), 'w');
  const child = spawn(executable, [`--user-data-dir=${path.join(root, 'artifacts/native-profile')}`, `--extensions-dir=${path.join(root, 'artifacts/host-extensions')}`, `--extensionDevelopmentPath=${root}`, `--extensionTestsPath=${path.join(root, 'test/native-ui-host.js')}`, `--remote-debugging-port=${port}`, '--disable-workspace-trust', '--skip-welcome', '--skip-release-notes', '--disable-updates', '--disable-gpu'], { env, windowsHide: true, stdio: ['ignore', log, log] });
  fsSync.closeSync(log);
  const exit = new Promise(resolve => child.on('exit', resolve));
  let browser;
  try {
    const deadline = Date.now() + 60000;
    let ready = false;
    while (Date.now() < deadline && child.exitCode === null) { try { await fs.access(path.join(directory, 'ready')); ready = true; break; } catch {} await wait(300); }
    assert.ok(ready, 'extension host ready');
    browser = await chromium.connectOverCDP(`http://127.0.0.1:${port}`);
    const page = browser.contexts().flatMap(context => context.pages()).find(page => page.url().includes('workbench'));
    assert.ok(page, 'isolated VS Code renderer found');
    const hover = page.locator('.monaco-hover').filter({ hasText: 'Codex Code Explainer' }).last();
    await hover.waitFor({ state: 'visible' });
    await page.waitForFunction(() => [...document.querySelectorAll('.monaco-hover')].some(el => el.textContent.includes('Codex Code Explainer') && !el.querySelector('.loading')));
    await hover.locator('a').filter({ hasText: 'Save note' }).waitFor();
    await page.waitForTimeout(400);
    await page.screenshot({ path: path.join(root, 'artifacts/native-hover.png') });
    await hover.locator('a').filter({ hasText: /^\s*Follow up\s*$/ }).click();
    const input = page.locator('.quick-input-widget input').first();
    await input.fill('Can parameter name be renamed?'); await input.press('Enter');
    await hover.getByText('It can be renamed.', { exact: false }).waitFor();
    await hover.locator('a').filter({ hasText: 'Follow up with quote' }).click();
    await input.press('Enter');
    await page.locator('.quick-input-title').filter({ hasText: 'Quoted follow-up' }).waitFor();
    await input.fill('Briefly explain this origin again.'); await input.press('Enter');
    await hover.getByText('Briefly explain this origin again.', { exact: false }).waitFor();
    await hover.locator('a').filter({ hasText: 'Settings' }).click();
    await input.fill('Reasoning effort'); await input.press('Enter');
    await input.fill('low'); await input.press('Enter');
    await hover.getByText('ui-test / low', { exact: false }).waitFor();
    await hover.locator('a').filter({ hasText: 'Save note' }).click();
    await hover.getByText('Short note saved.', { exact: false }).waitFor();
    assert.ok((await fs.readFile(path.join(directory, 'notes.md'), 'utf8')).includes('### Origin'));
    const calls = JSON.parse(await fs.readFile(path.join(directory, 'calls.json'), 'utf8'));
    assert.equal(calls.length, 4);
    assert.ok(calls[2].prompt.includes('The user quoted this passage from your explanation'));
    assert.equal(calls[3].settings.effort, 'low');
    await fs.writeFile(path.join(directory, 'result.json'), JSON.stringify({ nativeHover: true, followup: true, quote: true, settings: true, notes: true, calls: calls.length }, null, 2));
    console.log('PASS: Native hover follow-up, quote, reasoning effort, and note-saving controls clicked; screenshot generated.');
  } finally {
    await fs.writeFile(path.join(directory, 'done'), 'done');
    await Promise.race([exit, wait(10000)]);
    if (child.exitCode === null) child.kill();
    await browser?.close().catch(() => {});
  }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
